# fly.toml app configuration file generated for radiology-report-simpilifier on 2026-04-15T14:53:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'radiology-report-simpilifier'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
